// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_qinv
Rcpp::List C_qinv(SEXP AA);
RcppExport SEXP _fmesher_C_qinv(SEXP AASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    rcpp_result_gen = Rcpp::wrap(C_qinv(AA));
    return rcpp_result_gen;
END_RCPP
}
// fmesher_triangulate
Rcpp::List fmesher_triangulate(Rcpp::List args_input);
RcppExport SEXP _fmesher_fmesher_triangulate(SEXP args_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args_input(args_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(fmesher_triangulate(args_input));
    return rcpp_result_gen;
END_RCPP
}
// C_matrixio_test
Rcpp::List C_matrixio_test(Rcpp::List args_input);
RcppExport SEXP _fmesher_C_matrixio_test(SEXP args_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args_input(args_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(C_matrixio_test(args_input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmesher_C_qinv", (DL_FUNC) &_fmesher_C_qinv, 1},
    {"_fmesher_fmesher_triangulate", (DL_FUNC) &_fmesher_fmesher_triangulate, 1},
    {"_fmesher_C_matrixio_test", (DL_FUNC) &_fmesher_C_matrixio_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmesher(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
