#' @title Example 3D mesh data
#' @docType data
#' @description This is an example data set used for `fmesher` package examples.
#'
#' @usage
#' fmexample3d
#'
#' @format The data is a list containing these elements:
#'  \describe{
#'    \item{`loc`:}{ A `matrix` of points.}
#'    \item{`mesh`:}{ An [fm_mesh_3d()] object.}
#'  }
#' @source
#' Generated by `data-raw/fmexample.R`.
#' @seealso [fmexample], [fm_as_mesh_2d()]
#' @examples
#' if (require(ggplot2, quietly = TRUE)) {
#'   ggplot() +
#'     geom_sf(data = fm_as_sfc(fm_as_mesh_2d(fmexample3d$mesh)))
#' }
"fmexample3d"
