# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fmesher_main <- function(args_input) {
    .Call(`_fmesher_fmesher_main`, args_input)
}

#' Compute sparse matrix inverse
#'
#' @param A text
#' @export
qinv <- function(AA) {
    .Call(`_fmesher_qinv`, AA)
}

#' Main
#'
C_cmdline_test <- function(args_input) {
    .Call(`_fmesher_C_cmdline_test`, args_input)
}

#' Triangulate
#'
#' @export
fmesher_triangulate <- function(args_input) {
    .Call(`_fmesher_fmesher_triangulate`, args_input)
}

#' Test the matrix I/O system
#'
#' @param AA A sparse matrix
C_matrixio_test <- function(args_input) {
    .Call(`_fmesher_C_matrixio_test`, args_input)
}

