# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fmesher_main <- function(args_input) {
    .Call(`_fmesher_fmesher_main`, args_input)
}

#' Compute sparse matrix inverse
#'
#' @param A text
#' @export
qinv <- function(AA) {
    .Call(`_fmesher_qinv`, AA)
}

